config system global
 set hostname "FGT01"
end

config system interface
 edit "port1"
  set ip 192.168.10.1 255.255.255.0
  set allowaccess ssh https
 next
end

config firewall policy
 edit 1
  set action accept
 next
end
